//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rostr
{
    using System;
    using System.Collections.Generic;
    
    public partial class GaleItem
    {
        public int id_GI { get; set; }
        public string Title { get; set; }
        public byte[] Photo { get; set; }
        public int User_id { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
